### ISSUE TITLE
Parenthesis warnings with synchronous code

### ISSUE THREAD

**Issue by marioortizmanero** [fMeow/maybe-async-rs#1]
Hello! First of all, thanks a lot for creating this crate! It's super useful, we're using it at https://github.com/ramsayleung/rspotify.

The only problem we've found is that when `maybe-async/is_sync` is activated, these warnings appear:

```
warning: unnecessary parentheses around block return value
  --> src/lib.rs:11:12
   |
11 |     base().await
   |            ^^^^^ help: remove these parentheses
   |
   = note: `#[warn(unused_parens)]` on by default
```

Here's a minimal snippet:

```rust
//! lib.rs
use maybe_async::{sync_impl, maybe_async};

#[sync_impl]
fn base() -> ureq::Response {
  ureq::get("https://myapi.example.com/ingest")
      .call()
}

#[maybe_async]
pub async fn current_user() -> ureq::Response {
    base().await
}
```

```toml
# Cargo.toml
[package]
name = "notworking"
version = "0.1.0"
authors = ["Mario Ortiz Manero <marioortizmanero@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.40"
maybe-async = "0.2.0"
ureq = "1.4.1"

[features]
default = ["maybe-async/is_sync"]
```

Any idea of what this could be? Thanks in advance.
